# Generated by Django 6.0.4 on 2026-05-13 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_email_verified_profile_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
