# Generated by Django 6.0.4 on 2026-05-22 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_token_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
