"""
Django settings for auth_core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'accounts.apps.AccountsConfig',
    'django_cleanup.apps.CleanupConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # about google authentication
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    #about security shield over your login screens
    'axes',
]

SITE_ID = 2

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware', # <-- Add this right under auth middleware!
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Add this line here for google:
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'auth_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auth_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'nexus_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'your_postgres_password'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


# linking my CSS file
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# Tell django to point to this USER model
AUTH_USER_MODEL = 'accounts.CustomUserModel'


# About my Login
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# ------About Media Files (Pictures & Images)-----#
# The URL used to access the files in the browser
MEDIA_URL = '/media/'

# The actual file system path where files will be stored
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# ------ Enable Email Verification -----#
# 1. Switch to the SMTP Backend
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 2. Gmail SMTP Server Settings
EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

# 3. Your Credentials
EMAIL_HOST_USER = 'igbedean@gmail.com' 
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# 4. Branded Sender
DEFAULT_FROM_EMAIL = 'Nexus Identity <igbedean@gmail.com>'


# ------ Enable authentication through third party (Google) -----#
# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend', # <-- Keeps track of 
    
    # 1. Needed to login by username/password in Django admin, regardless of allauth
    'django.contrib.auth.backends.ModelBackend',

    # 2. `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Social Account Settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',  # This is the magic line
        },
    }
}

# Tell allauth to use Email instead of Username
# 1. This handles how people log in
ACCOUNT_LOGIN_METHODS = {'email'}

# 2. This handles how people sign up (No username here = not required)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

# 3. This tells the engine your model doesn't use usernames at all
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

ACCOUNT_ADAPTER = 'accounts.adapter.NoMessagesAdapter'

# This skips the intermediate "Sign In" confirmation page
SOCIALACCOUNT_LOGIN_ON_GET = True

# 1. Automatically trust verified emails from OAuth providers to log users into existing accounts
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True

# 2. Automatically link the social login to the existing user profile permanently on successful match
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

# Optional: Tells allauth not to generate its default internal text strings
ACCOUNT_SET_FLAG_SESSION_VARIABLES = True




# Define the Defensive Firewall Rules
from datetime import timedelta

# --- NEXUS SECURITY SHIELD (AXES CONFIG) ---
# Lock out after 5 consecutive failed attempts
AXES_FAILURE_LIMIT = 5

# Lock out parameters: block by combination of IP and Username
# Add the modern equivalent:
AXES_LOCKOUT_PARAMETERS = [
    ["username", "ip_address"],
]

# Cooldown block duration: How long are they banned? (e.g., 30 minutes)
AXES_COOLOFF_TIME = timedelta(minutes=30)

# Reset failed attempt counter instantly on a successful login
AXES_RESET_ON_SUCCESS = True

# Since you use email for logging in, tell Axes the field name in your POST request
AXES_USERNAME_FORM_FIELD = 'username'

# Point this to the exact import path of your new view function
AXES_LOCKOUT_CALLABLE = 'accounts.views.axes_lockout_view'